baseURL = "https://skushagra.com"
languageCode = 'en-us'
title = 'Declarative'
[pagination]
  pagerSize = 10
[params]
  description = 'fewer segfaults, more semantics'
  github = "suobset"
  linkedin = "suobset"
  orcid = "0000-0003-0656-5478"
  instagram = "suobset"