baseURL = "https://skushagra.com"
languageCode = 'en-us'
title = 'Declarative'
[pagination]
  pagerSize = 12
[params]
  description = 'by Kush S.'
  github = "suobset"
  linkedin = "suobset"
  orcid = "0000-0003-0656-5478"